/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ProtectedVocabularyRouteImport } from './routes/_protected/vocabulary'
import { Route as ProtectedLibraryRouteImport } from './routes/_protected/library'
import { Route as ProtectedExploreRouteImport } from './routes/_protected/explore'
import { Route as PublicAuthRouteRouteImport } from './routes/_public/_auth/route'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/_auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedVocabularyRoute = ProtectedVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLibraryRoute = ProtectedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedExploreRoute = ProtectedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicAuthRouteRoute = PublicAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/explore': typeof ProtectedExploreRoute
  '/library': typeof ProtectedLibraryRoute
  '/vocabulary': typeof ProtectedVocabularyRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/explore': typeof ProtectedExploreRoute
  '/library': typeof ProtectedLibraryRoute
  '/vocabulary': typeof ProtectedVocabularyRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/_auth': typeof PublicAuthRouteRouteWithChildren
  '/_protected/explore': typeof ProtectedExploreRoute
  '/_protected/library': typeof ProtectedLibraryRoute
  '/_protected/vocabulary': typeof ProtectedVocabularyRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/register': typeof PublicAuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/library'
    | '/vocabulary'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore' | '/library' | '/vocabulary' | '/login' | '/register'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_public/_auth'
    | '/_protected/explore'
    | '/_protected/library'
    | '/_protected/vocabulary'
    | '/_public/'
    | '/_public/_auth/login'
    | '/_public/_auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/vocabulary': {
      id: '/_protected/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof ProtectedVocabularyRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/library': {
      id: '/_protected/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ProtectedLibraryRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/explore': {
      id: '/_protected/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ProtectedExploreRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth/register': {
      id: '/_public/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedExploreRoute: typeof ProtectedExploreRoute
  ProtectedLibraryRoute: typeof ProtectedLibraryRoute
  ProtectedVocabularyRoute: typeof ProtectedVocabularyRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedExploreRoute: ProtectedExploreRoute,
  ProtectedLibraryRoute: ProtectedLibraryRoute,
  ProtectedVocabularyRoute: ProtectedVocabularyRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicAuthRouteRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
}

const PublicAuthRouteRouteChildren: PublicAuthRouteRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
}

const PublicAuthRouteRouteWithChildren = PublicAuthRouteRoute._addFileChildren(
  PublicAuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthRouteRoute: typeof PublicAuthRouteRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRouteRoute: PublicAuthRouteRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
